pipeline {
    agent any

    stages {
        stage("Install requirements"){
            agent {docker {image 'python'}}
            steps {
                sh '''
                echo "EXECUTING INSTALLATION OF PYTHON PACKAGES"
                pip3 install --upgrade pip
                pip3 install virtualenv
                PYENV_HOME=$WORKSPACE/.pyenv/
                virtualenv $PYENV_HOME
                source $PYENV_HOME/bin/activate
                pip3 install -U pytest
                pip3 install -r requirements.txt
                '''
            }
        }
        stage("Run script") {
            steps {
                sh "chmod +x '1 Basic Python Jenkins Pipeline/tests/dumy_test.py'"
                sh "python3 '1 Basic Python Jenkins Pipeline/tests/dumy_test.py'"
            }
        }
        stage("Run Parametrized Test script") {
            steps {
                sh "chmod +x '1 Basic Python Jenkins Pipeline/tests/parametrize_tests.py'"
                sh "python3 '1 Basic Python Jenkins Pipeline/tests/parametrize_tests.py'"

            }
        }
    }
}
