pipeline {
    agent any

    stages {
        stage("Install requirements"){
            steps {
                sh """
                apt-get install python3-venv -y
                python3 -m venv venv
                source venv/bin/activate
                pip install -r requirements.txt
                """
            }
        }
        stage("Run script") {
            steps {
                sh "chmod +x '1 Basic Python Jenkins Pipeline/tests/dumy_test.py'"
                sh "python3 '1 Basic Python Jenkins Pipeline/tests/dumy_test.py'"
            }
        }
        stage("Run Parametrized Test script") {
            steps {
                sh "chmod +x '1 Basic Python Jenkins Pipeline/tests/parametrize_tests.py'"
                sh "python3 '1 Basic Python Jenkins Pipeline/tests/parametrize_tests.py'"

            }
        }
    }
}

