pipeline {
    agent {docker {image 'python:3.5.2-alpine'}}

    stages {
        stage("Install requirements"){
            steps {
                sh '''
                echo "EXECUTING INSTALLATION OF PYTHON PACKAGES"
                PYENV_HOME=./pyenv
                python -m venv $PYENV_HOME
                source $PYENV_HOME/bin/activate
                pip3 install -U pytest
                pip3 install -r requirements.txt
                '''
            }
        }
        stage("Run script") {
            steps {
                sh '''
                PYENV_HOME=./pyenv
                source $PYENV_HOME/bin/activate
                '''
                sh "chmod +x '1 Basic Python Jenkins Pipeline/tests/dumy_test.py'"
                sh "python3 '1 Basic Python Jenkins Pipeline/tests/dumy_test.py'"
            }
        }
        stage("Run Parametrized Test script") {
            steps {
                sh '''
                PYENV_HOME=./pyenv
                source $PYENV_HOME/bin/activate
                '''

                sh "chmod +x '1 Basic Python Jenkins Pipeline/tests/parametrize_tests.py'"
                sh "python3 '1 Basic Python Jenkins Pipeline/tests/parametrize_tests.py'"

            }
        }
    }
}
